- hosts: ansible-client-eth0
  remote_user: root

  tasks:
   - name: stop Apache
     service:
        name=httpd.service
        state=stopped
   - name: remove apache
     yum: 
       name={{ item }}
       state=absent
     with_items:
       - httpd
       - httpd-devel