- hosts: linux-ens160
  remote_user: root
  tasks:
  - name: change xiaotiantian
    shell: echo '{{ item.password }}' | passwd --stdin xiaotiantian
    when: ansible_ens160.ipv4.address == '{{ item.ipaddress }}'
    with_items:
      - { ipaddress: '10.0.1.121', password: '123456' }