- hosts: ansible-client-eth0
  remote_user: root
  tasks:
  - name: change xiaotiantian
    shell: echo item.password | passwd --stdin xiaotiantian
    when: ansible_eth0.ipv4.address == item.ipaddress
    with_items:
      - { ipaddress: '172.16.101.133', password: '1234567' }